# Generated by Django 4.2.7 on 2025-08-01 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('sensor', 'Physical Sensor'), ('api', 'External API')], max_length=10)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('aqi', models.IntegerField(help_text='The primary Air Quality Index value')),
                ('pm25', models.FloatField(blank=True, null=True, verbose_name='PM2.5')),
                ('pm10', models.FloatField(blank=True, null=True, verbose_name='PM10')),
                ('co', models.FloatField(blank=True, null=True, verbose_name='CO')),
                ('no2', models.FloatField(blank=True, null=True, verbose_name='NO2')),
                ('so2', models.FloatField(blank=True, null=True, verbose_name='SO2')),
                ('o3', models.FloatField(blank=True, null=True, verbose_name='O3')),
                ('temperature', models.FloatField(blank=True, help_text='in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='in %', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='in hPa', null=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Good, Moderate', max_length=100, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Store original data from source if needed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Air Quality Reading',
                'verbose_name_plural': 'Air Quality Readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_ahead', models.IntegerField(help_text='How many hours into the future this prediction is for (e.g., 24, 48)')),
                ('predicted_aqi', models.FloatField()),
                ('model_used', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='air_quality.airqualityreading')),
            ],
            options={
                'verbose_name': 'AQI Prediction',
                'verbose_name_plural': 'AQI Predictions',
                'ordering': ['reading', 'hours_ahead'],
            },
        ),
    ]
