# Generated by Django 4.2.7 on 2025-08-01 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_used', models.CharField(help_text='Identifier for the model that generated this forecast', max_length=100)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastDataPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_for_date', models.DateField()),
                ('predicted_aqi', models.FloatField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='air_quality.forecast')),
            ],
            options={
                'ordering': ['forecast_for_date'],
                'unique_together': {('forecast', 'forecast_for_date')},
            },
        ),
    ]
