# Generated by Django 4.2.7 on 2025-07-17 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air_quality', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField(default=0)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_air_quality', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='airqualitydata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='co',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='no2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='o3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='pm10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='so2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AQIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_ahead', models.IntegerField(default=24)),
                ('predicted_aqi', models.FloatField()),
                ('model_used', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('air_quality_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='air_quality.airqualityrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
