# Generated by Django 4.2.7 on 2025-08-01 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air_quality', '0002_forecast_forecastdatapoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQIForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='airqualityreading',
            options={},
        ),
        migrations.AlterModelOptions(
            name='forecastdatapoint',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='forecastdatapoint',
            old_name='forecast_for_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='airqualityreading',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='airqualityreading',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='airqualityreading',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='airqualityreading',
            name='aqi',
            field=models.IntegerField(blank=True, help_text='Overall Air Quality Index', null=True),
        ),
        migrations.AlterField(
            model_name='airqualityreading',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityreading',
            name='o3',
            field=models.FloatField(blank=True, null=True, verbose_name='Ozone (O3)'),
        ),
        migrations.AlterField(
            model_name='airqualityreading',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityreading',
            name='source',
            field=models.CharField(choices=[('api', 'API'), ('sensor', 'Sensor'), ('FRIEND_API', 'Friend API')], default='api', max_length=20),
        ),
        migrations.AlterField(
            model_name='airqualityreading',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='airqualityreading',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forecastdatapoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.AlterUniqueTogether(
            name='forecastdatapoint',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='forecastdatapoint',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='air_quality.aqiforecast'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastdatapoint',
            unique_together={('forecast', 'date')},
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
