# Generated by Django 4.2.7 on 2025-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('overall_aqi', models.IntegerField()),
                ('dominant_pollutant', models.CharField(max_length=20)),
                ('dominant_concentration', models.FloatField()),
                ('individual_aqis', models.JSONField()),
                ('concentrations', models.JSONField()),
                ('category_info', models.JSONField()),
            ],
        ),
    ]
