# Generated by Django 4.2.7 on 2025-08-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AQILog',
        ),
    ]
